### ISSUE TITLE
multiple typos in readme.md

### ISSUE THREAD

**Issue by Parikshit-Hooda** [LoginRadius/engineering-blog-samples#23]
search for 'respository', 'langauge', and 'partciular' in README.md file.
Raising and fixing during hacktoberfest'2020.

**Comment by appsplash99** [comment]
Can you assign it to me? 😄 
I am new to opensource.

**Comment by dhritippaul** [comment]
Hello @Parikshit-Hooda I would like to fix the typo present in the README.md file. I would be following the contribution guide and do the needful. So, kindly assign me to fix the typo.

**Comment by Gauravsaha-97** [comment]
I would like to work on this issue.

**Comment by Parikshit-Hooda** [comment]
Guys, I've already raised the PR.
