### ISSUE TITLE
lang attribute in HTML Tag.

### ISSUE THREAD

**Issue by thelovekesh** [LoginRadius/engineering-blog-samples#81]
You should have a language attribute in all HTML pages. 
```
<!DOCTYPE html>
<html lang="en">
.
.
.
</html>
```
According to the W3C Standards Always declare the default language for text in the page using attributes on the HTML tag.
[Read more here](https://www.w3.org/International/techniques/authoring-html.en?open=language&open=textprocessing#textprocessing)

**Comment by Parimalisgreat** [comment]
@thelovekesh  , can I take it ?
